title: "AWSのセキュリティに関すること"
summary: |-
  【この本について】
  AWSのセキュリティに関することをまとめていきます

  【本書の構成】
  - 第00章 はじめに
  - 第01章 IAM
  - 第02章 VPC

  【更新情報】
  2023/03/31 新規作成

  【感想】
  感想は下記scrapに投稿をお願い致します。

  【ご指摘】
  下記GitHubにてissueを作成してくださると嬉しいです。

# 未公開
# - 第03章
# - 第04章
# - 第05章
# - 第06章
# - 第07章
# - 第08章
# - 第09章
# - 第10章
# - 第11章

topics: ["AWS", "セキュリティ"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 00_introduction
  - 01_iam_single-tenant
  - 01_iam_multi-tenant
toc_depth: 1
